//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_shooter : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.shooter_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reload
        {
            get
            {
                return SteamVR_Actions.shooter_Reload;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cancel
        {
            get
            {
                return SteamVR_Actions.shooter_Cancel;
            }
        }
    }
}
