//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_gun : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single Grip
        {
            get
            {
                return SteamVR_Actions.gun_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.gun_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.gun_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.gun_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.gun_Fire;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Stick
        {
            get
            {
                return SteamVR_Actions.gun_Stick;
            }
        }
        
        public virtual SteamVR_Action_Boolean StickDown
        {
            get
            {
                return SteamVR_Actions.gun_StickDown;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.gun_Haptic;
            }
        }
    }
}
